### ISSUE TITLE
 raise ValueError("columns cannot be a set")

### ISSUE THREAD

**Issue by glennin-codes** [memudualimatou/STUDENT-ATTENDANCE-USING-FACIAL-RECOGNITION-SYSTEM-OPENCV#9]
**i keep getting this error whwnever i click trained image button and track Image button** 
    _attendance = pd.DataFrame(columns=col_names)
  File "/home/glennin/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 639, in __init__
    raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/glennin/Desktop/STUDENT-ATTENDANCE-USING-FACIAL-RECOGNITION-SYSTEM-OPENCV/attendance.py", line 114, in trackImage
    attendance = pd.DataFrame(columns=col_names)
  File "/home/glennin/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 639, in __init__
    raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set_

**Comment by glennin-codes** [comment]
was able to find solution

**Comment by glennin-codes** [comment]
solution found

**Comment by memudualimatou** [comment]
I am so sorry I totally forgot to reply you , how did you solve it
